### ISSUE TITLE
divoom platform not found in notify devices.

### ISSUE THREAD

**Issue by donster22** [d03n3rfr1tz3/hass-divoom#12]
hi. setup as per the instructions i believe, but when i look for the service in notify, all of my phones etc are there but there is no divoom device. is this integration still working? also, the divoom app makes me login before i can pair with and interact with my Pixoo. how does the integration bypass this? cheers.

**Comment by t1n00** [comment]
Got it also not working. No new notify in services 😢

**Comment by d03n3rfr1tz3** [comment]
there will be no device in your home assistant. it just exposes a new notify-service, which you can use to send commands to your Divoom device. for example like this for the clock 
![grafik](https://github.com/d03n3rfr1tz3/hass-divoom/assets/1483070/09f425a9-f4f4-4500-8627-1ea8ad09fd3a)
there is also a full list of examples for the supported modes here: https://github.com/d03n3rfr1tz3/hass-divoom/blob/main/devices/pixoo.txt

regarding the question with the login: the integration directly communicates with the Divoom devices via a bluetooth socket. it only needs to be paired, which works like pairing a bluetooth speaker. the mobile app does basically the same, but the app itself requires you to login, not your Divoom device. its a decision by the app developers to require every user to login.
