### ISSUE TITLE
Can't get the service to run

### ISSUE THREAD

**Issue by rodolfoleo** [d03n3rfr1tz3/hass-divoom#26]
Hi! I've followed the installation instructions yet I can't get the notification service to appear in HA (tried calling it in dev tools after restarting)... I added some pictures of my installation. Could anybody tell me what's wrong?

Thank You!

Folder Structure:

![Screen Shot 2024-03-30 at 20 52 19](https://github.com/d03n3rfr1tz3/hass-divoom/assets/9421016/d6b0b90c-f26f-4c96-ba97-3a1fd1e94210)

config.yaml:

![Screen Shot 2024-03-30 at 20 53 26](https://github.com/d03n3rfr1tz3/hass-divoom/assets/9421016/c00fa3ac-dce5-4742-be78-2793a0531ec8)

Developer Tools Service Call:

![Screen Shot 2024-03-30 at 20 56 01](https://github.com/d03n3rfr1tz3/hass-divoom/assets/9421016/74bbd548-4259-4523-b90b-bc30768b2d58)

**Comment by d03n3rfr1tz3** [comment]
looks very much good to me. the entry in your configuration.yaml is fine and also the directory/file structure. therefore it should work. besides the chosen name 'pixoo' and the mac address obviously, it looks similar to mine.

is there anything in the logs, aside from the currently known error regarding 'custom_components.divoom.config_flow' (which doesnt stop the component from working)?

**Comment by rodolfoleo** [comment]
Thanks a lot for your answer! After posting this I remembered that you can add an integration in HA's Devices & Services -> Add Integration. I did so and searched for Divoom and your package did show up. Obviously it can't be installed that way but it shows in there so it is placed in the right folder structure, as you said.

This narrows down my problem to the configuration.yaml ...I don't know how to check for such errors in HA's logs (I'm using Home Assistant OS on a Raspberry Pi 4, btw)... I'll check on it and report back.

**Comment by rodolfoleo** [comment]
Found this python error within the logs

```
Logger: homeassistant.components.notify
Source: components/notify/legacy.py:94
integration: Notifications (documentation, issues)
First occurred: 5:02:02 AM (1 occurrences)
Last logged: 5:02:02 AM

Error setting up platform divoom
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 94, in async_setup_platform
    notify_service = await hass.async_add_executor_job(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/divoom/notify.py", line 84, in get_service
    return DivoomNotificationService(mac, port, device_type, media_directory, escape_payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/divoom/notify.py", line 113, in __init__
    if self._device is None:
       ^^^^^^^^^^^^
AttributeError: 'DivoomNotificationService' object has no attribute '_device'

```

After that error, there's this other one...

```
[Logger: homeassistant.config_entries
Source: config_entries.py:2444
First occurred: 5:02:19 AM (2 occurrences)
Last logged: 5:02:19 AM

Error occurred loading flow for integration divoom: No module named 'custom_components.divoom.config_flow']
```

**Comment by d03n3rfr1tz3** [comment]
ahhhh.... that error basically means, that it's missing a valid ´device_type´. therefore I had a closer look at your configuration.yaml content and saw the reason. look how your quotes around the value `pixoo` is different. replace them with the quotes you have around `pixelart` and the error should be gone.

btw, if you wait a little bit (maybe a few hours), I might have an update ready, that allows you to configure everything through the UI. I only working on duplicate checks and some text stuff.

**Comment by rodolfoleo** [comment]
You are ABSOLUTELY right, it's the quotes that are the problem! You're genius! I wrote the data in the notes app in my Mac and copied it straight to the yaml... and those are not the standard quotes. Thank you!

I'm looking forward for the update... it'll be awesome to simplify the configuration.

Thanks again!
