### ISSUE TITLE
OSError: [Errno 93] Protocol not supported

### ISSUE THREAD

**Issue by schutzmuster** [d03n3rfr1tz3/hass-divoom#5]
Hi, I hope you can help me. I really like to use your work together with an MS-Teams Status Monitor in HA.

My System is a VM inside of an Synology:
Home Assistant OS 7.4
supervisor-2022.03.4
core-2022.3.4

In HA Terminal i can start bluetoothctl
My BT Device is running & my pixoo is connected/paired
<img width="408" alt="image" src="https://user-images.githubusercontent.com/91045574/158225948-cfb2328c-4393-4231-8a5e-11fdd3b3ad8a.png">

My configuration.yaml
notify:
  - name: PIXOO
    platform: divoom
    mac: "11:75:58:48:29:D2"
    device_type: "pixoo"
    media_directory: "/pixelart"

Traceback:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 65, in async_setup_platform
    notify_service = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/divoom/notify.py", line 52, in get_service
    return DivoomNotificationService(mac, device_type, media_directory)
  File "/config/custom_components/divoom/notify.py", line 64, in __init__
    self._device.connect()
  File "/config/custom_components/divoom/devices/pixoo.py", line 40, in connect
    self.socket = socket.socket(socket.AF_BLUETOOTH, socket.SOCK_STREAM, socket.BTPROTO_RFCOMM)
  File "/usr/local/lib/python3.9/socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 93] Protocol not supported

Did I miss something in the configuration or does HA needs additionell driver/software?

Thank you very much for your work and time.

**Comment by d03n3rfr1tz3** [comment]
Did you go throw this [guide](https://www.pcsuggest.com/linux-bluetooth-setup-hcitool-bluez/), that is also linked in the Readme? Because it looks like bluez is missing or at least that would be the typical error if it is missing.

**Comment by d03n3rfr1tz3** [comment]
Yeah AFAIK its currently not possible with hassio. But I found out, that it might be possible to create a component that does the bluetooth communication hosted in docker, which then could contain the necessary dependencies. I'd have to rebuild a lot, so that's something for the future, I guess.

**Comment by francescoditrani** [comment]
I made it work in hassio using bluetoothctl. After scanning to get the MAC address I did a: "pair MAC", "trust MAC" and "connect MAC" and it worked.

**Comment by d03n3rfr1tz3** [comment]
Sounds great. Is there something I could/should add to the Readme? Would be nice if we could advise others to get it working on hassio.
